In [21]:
import pandas as pd

In [10]:
df = pd.read_excel("G:\github-aditya0by0\python-chebai-graph\classwise_f1_score.xlsx")
df.head()

,label,res_baseline_props,res_wfgn_wfge_wgn_wprops_apool,gatv2_wfgn_wfge_wgn_wprops_apool,gatv2 - baseline,res - baseline
0,146180,0.0,0.0000,0.0000,0.0000,0.0000
1,60004,0.0,0.1176,0.0000,0.0000,0.1176
2,16733,0.0,0.2353,0.0000,0.0000,0.2353
3,22299,0.0,0.2857,0.0000,0.0000,0.2857
4,17815,0.0,0.1250,0.1111,0.1111,0.1250

In [18]:
df.shape

(1528, 6)

In [13]:
df.columns

Index(['label', 'res_baseline_props', 'res_wfgn_wfge_wgn_wprops_apool',
       'gatv2_wfgn_wfge_wgn_wprops_apool', 'gatv2 - baseline ',
       'res - baseline'],
      dtype='object')

In [14]:
BASELINE = "res_baseline_props"
RES = "res_wfgn_wfge_wgn_wprops_apool"
GATv2 = "gatv2_wfgn_wfge_wgn_wprops_apool"
GATv2_BASELINE_DIFF = "gatv2 - baseline "
RES_BASELINE_DIFF = "res - baseline"

### Summary statistics

Look at the overall performance:

In [16]:
# mean improvement
mean_diff = df[[RES_BASELINE_DIFF, GATv2_BASELINE_DIFF]].mean()
print("Mean improvement over baseline:\n", mean_diff)
print()

# median improvement
median_diff = df[[RES_BASELINE_DIFF, GATv2_BASELINE_DIFF]].median()
print("Median improvement over baseline:\n", median_diff)
print()


# standard deviation of improvements
std_diff = df[[RES_BASELINE_DIFF, GATv2_BASELINE_DIFF]].std()
print("Variation in improvement:\n", std_diff)

Mean improvement over baseline:
 res - baseline       0.054853
gatv2 - baseline     0.068136
dtype: float64

Median improvement over baseline:
 res - baseline       0.03330
gatv2 - baseline     0.04535
dtype: float64

Variation in improvement:
 res - baseline       0.144831
gatv2 - baseline     0.139299
dtype: float64

### Count of labels improved / worsened

In [19]:
res_improvement = (df[RES_BASELINE_DIFF] > 0).sum()
gat_v2_improvement = (df[GATv2_BASELINE_DIFF] > 0).sum()

print(f"Labels improved in ResGated Final model over baseline: {res_improvement}")
print(f"Labels improved in GATv2 Final model over baseline: {gat_v2_improvement}")

Labels improved in ResGated Final model over baseline: 1010
Labels improved in GATv2 Final model over baseline: 1091

### Ranking per label

In [27]:
df["best_model"] = df[[BASELINE, RES, GATv2]].idxmax(axis=1)
print(df["best_model"].value_counts())

best_model
gatv2_wfgn_wfge_wgn_wprops_apool    678
res_wfgn_wfge_wgn_wprops_apool      524
res_baseline_props                  326
Name: count, dtype: int64

In [32]:
# Classes with highest difference
top_diff_res = df[RES_BASELINE_DIFF].sort_values(ascending=False).head(10)
print(
    f"\nTop 10 classes with highest improvement for {RES_BASELINE_DIFF}:\n",
    top_diff_res,
)

top_diff_gat = df[GATv2_BASELINE_DIFF].sort_values(ascending=False).head(10)
print(
    f"\nTop 10 classes with highest improvement for {GATv2_BASELINE_DIFF}:\n",
    top_diff_res,
)

Top 10 classes with highest improvement for res - baseline:
 25    0.8889
24    0.8889
37    0.7692
34    0.7143
35    0.7143
29    0.7143
77    0.6889
41    0.6487
36    0.6400
23    0.6364
Name: res - baseline, dtype: float64

Top 10 classes with highest improvement for gatv2 - baseline :
 25    0.8889
24    0.8889
37    0.7692
34    0.7143
35    0.7143
29    0.7143
77    0.6889
41    0.6487
36    0.6400
23    0.6364
Name: res - baseline, dtype: float64

In [ ]:
# Classes with minimal or no difference
minimal_diff_threshold = 0.01  # you can adjust
minimal_diff = df[df[RES_BASELINE_DIFF].abs() <= minimal_diff_threshold]
minimal_diff

,label,res_baseline_props,res_wfgn_wfge_wgn_wprops_apool,gatv2_wfgn_wfge_wgn_wprops_apool,gatv2 - baseline,res - baseline,best_model
0,146180,0.0,0.0,0.0000,0.0000,0.0,res_baseline_props
9,25711,0.0,0.0,0.2500,0.2500,0.0,gatv2_wfgn_wfge_wgn_wprops_apool
10,39093,0.0,0.0,0.2500,0.2500,0.0,gatv2_wfgn_wfge_wgn_wprops_apool
18,4194,0.0,0.0,0.4615,0.4615,0.0,gatv2_wfgn_wfge_wgn_wprops_apool
19,17608,0.0,0.0,0.4615,0.4615,0.0,gatv2_wfgn_wfge_wgn_wprops_apool
...,...,...,...,...,...,...,...
1523,76629,1.0,1.0,1.0000,0.0000,0.0,res_baseline_props
1524,78776,1.0,1.0,1.0000,0.0000,0.0,res_baseline_props
1525,79204,1.0,1.0,1.0000,0.0000,0.0,res_baseline_props
1526,132742,1.0,1.0,1.0000,0.0000,0.0,res_baseline_props
1527,136637,1.0,1.0,1.0000,0.0000,0.0,res_baseline_props

In [37]:
# Classes where baseline performs better
baseline_better = df[df[RES_BASELINE_DIFF] < 0]
print("\nClasses where baseline performs better than our model:\n", baseline_better)

Classes where baseline performs better than our model:
       label  res_baseline_props  res_wfgn_wfge_wgn_wprops_apool  \
45    59999              0.1176                          0.0541
47    59266              0.1176                          0.1143
50    25095              0.1333                          0.0000
70    48927              0.2000                          0.0000
72    83943              0.2000                          0.0000
...     ...                 ...                             ...
1508  24846              1.0000                          0.9333
1509  26187              1.0000                          0.9333
1510  78231              1.0000                          0.9333
1511  26377              1.0000                          0.9565
1512  38834              1.0000                          0.9677

      gatv2_wfgn_wfge_wgn_wprops_apool  gatv2 - baseline   res - baseline  \
45                              0.1250             0.0074         -0.0635
47                              0.5385             0.4209         -0.0033
50                              0.2667             0.1334         -0.1333
70                              0.0000            -0.2000         -0.2000
72                              0.2000             0.0000         -0.2000
...                                ...                ...             ...
1508                            1.0000             0.0000         -0.0667
1509                            1.0000             0.0000         -0.0667
1510                            1.0000             0.0000         -0.0667
1511                            1.0000             0.0000         -0.0435
1512                            1.0000             0.0000         -0.0323

                            best_model
45    gatv2_wfgn_wfge_wgn_wprops_apool
47    gatv2_wfgn_wfge_wgn_wprops_apool
50    gatv2_wfgn_wfge_wgn_wprops_apool
70                  res_baseline_props
72                  res_baseline_props
...                                ...
1508                res_baseline_props
1509                res_baseline_props
1510                res_baseline_props
1511                res_baseline_props
1512                res_baseline_props

[431 rows x 7 columns]

In [38]:
# Classes where both baseline and our model perform worse
# Assuming "worse" means below a threshold, e.g., f1 < 0.5
threshold = 0.5
both_worse = df[(df[BASELINE] < threshold) & (df[RES] < threshold)]
print(f"\nClasses where both baseline and {RES} have F1 < {threshold}:\n", both_worse)

Classes where both baseline and res_wfgn_wfge_wgn_wprops_apool have F1 < 0.5:
       label  res_baseline_props  res_wfgn_wfge_wgn_wprops_apool  \
0    146180              0.0000                          0.0000
1     60004              0.0000                          0.1176
2     16733              0.0000                          0.2353
3     22299              0.0000                          0.2857
4     17815              0.0000                          0.1250
..      ...                 ...                             ...
265   32877              0.4615                          0.4706
271  139358              0.4667                          0.4000
283   35346              0.4762                          0.4706
284   35507              0.4762                          0.4737
295   24586              0.4878                          0.4762

     gatv2_wfgn_wfge_wgn_wprops_apool  gatv2 - baseline   res - baseline  \
0                              0.0000             0.0000          0.0000
1                              0.0000             0.0000          0.1176
2                              0.0000             0.0000          0.2353
3                              0.0000             0.0000          0.2857
4                              0.1111             0.1111          0.1250
..                                ...                ...             ...
265                            0.5333             0.0718          0.0091
271                            0.5517             0.0850         -0.0667
283                            0.3529            -0.1233         -0.0056
284                            0.3871            -0.0891         -0.0025
295                            0.6667             0.1789         -0.0116

                           best_model
0                  res_baseline_props
1      res_wfgn_wfge_wgn_wprops_apool
2      res_wfgn_wfge_wgn_wprops_apool
3      res_wfgn_wfge_wgn_wprops_apool
4      res_wfgn_wfge_wgn_wprops_apool
..                                ...
265  gatv2_wfgn_wfge_wgn_wprops_apool
271  gatv2_wfgn_wfge_wgn_wprops_apool
283                res_baseline_props
284                res_baseline_props
295  gatv2_wfgn_wfge_wgn_wprops_apool

[148 rows x 7 columns]

In [40]:
# Classes where baseline performs better
baseline_better = df[df[RES_BASELINE_DIFF] < 0]
print("\nClasses where baseline performs better than our model:\n", baseline_better)

Classes where baseline performs better than our model:
       label  res_baseline_props  res_wfgn_wfge_wgn_wprops_apool  \
45    59999              0.1176                          0.0541
47    59266              0.1176                          0.1143
50    25095              0.1333                          0.0000
70    48927              0.2000                          0.0000
72    83943              0.2000                          0.0000
...     ...                 ...                             ...
1508  24846              1.0000                          0.9333
1509  26187              1.0000                          0.9333
1510  78231              1.0000                          0.9333
1511  26377              1.0000                          0.9565
1512  38834              1.0000                          0.9677

      gatv2_wfgn_wfge_wgn_wprops_apool  gatv2 - baseline   res - baseline  \
45                              0.1250             0.0074         -0.0635
47                              0.5385             0.4209         -0.0033
50                              0.2667             0.1334         -0.1333
70                              0.0000            -0.2000         -0.2000
72                              0.2000             0.0000         -0.2000
...                                ...                ...             ...
1508                            1.0000             0.0000         -0.0667
1509                            1.0000             0.0000         -0.0667
1510                            1.0000             0.0000         -0.0667
1511                            1.0000             0.0000         -0.0435
1512                            1.0000             0.0000         -0.0323

                            best_model
45    gatv2_wfgn_wfge_wgn_wprops_apool
47    gatv2_wfgn_wfge_wgn_wprops_apool
50    gatv2_wfgn_wfge_wgn_wprops_apool
70                  res_baseline_props
72                  res_baseline_props
...                                ...
1508                res_baseline_props
1509                res_baseline_props
1510                res_baseline_props
1511                res_baseline_props
1512                res_baseline_props

[431 rows x 7 columns]